// flow-typed signature: 2f865512a2a2828a1708201aae916908
// flow-typed version: <<STUB>>/hyperapp-devtools_v^0.3.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hyperapp-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hyperapp-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hyperapp-devtools/dist/hyperapp-devtools' {
  declare module.exports: any;
}

declare module 'hyperapp-devtools/dist/hyperapp-devtools.min' {
  declare module.exports: any;
}

declare module 'hyperapp-devtools/rollup.config' {
  declare module.exports: any;
}

declare module 'hyperapp-devtools/src/components/ObjectView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hyperapp-devtools/dist/hyperapp-devtools.js' {
  declare module.exports: $Exports<'hyperapp-devtools/dist/hyperapp-devtools'>;
}
declare module 'hyperapp-devtools/dist/hyperapp-devtools.min.js' {
  declare module.exports: $Exports<'hyperapp-devtools/dist/hyperapp-devtools.min'>;
}
declare module 'hyperapp-devtools/rollup.config.js' {
  declare module.exports: $Exports<'hyperapp-devtools/rollup.config'>;
}
declare module 'hyperapp-devtools/src/components/ObjectView.js' {
  declare module.exports: $Exports<'hyperapp-devtools/src/components/ObjectView'>;
}
