// flow-typed signature: 83293fe67048551c02b162b931d13d8c
// flow-typed version: <<STUB>>/hyperapp_v^1.2.6/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hyperapp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hyperapp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hyperapp/dist/hyperapp' {
  declare module.exports: any;
}

declare module 'hyperapp/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hyperapp/dist/hyperapp.js' {
  declare module.exports: $Exports<'hyperapp/dist/hyperapp'>;
}
declare module 'hyperapp/src/index.js' {
  declare module.exports: $Exports<'hyperapp/src/index'>;
}
